name: env_transit
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pandas
  - pyarrow
  - requests
  - pip
  - pip:
      - Flask
      - gtfs-realtime-bindings
      - google-cloud-bigquery
      - google-cloud-storage
      - python-dotenv
