name: env_transform_311
channels:
  - conda-forge
dependencies:
  - python=3.12
  - requests
  - pandas
  - numpy
  - matplotlib
  - geopandas
  - shapely
  - pip
  - pip:
      - google-cloud-storage
      - google-cloud-bigquery